#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code DD - 开发工作流系统"
echo "============================================="
echo ""
echo "🎯 核心开发工作流"
echo "  1. /dd:ctx-init                 - 初始化项目上下文"
echo "  2. /dd:prd-new <名称>           - 创建新的PRD"
echo "  3. /dd:prd-parse <名称>         - 转换PRD为Epic"
echo "  4. /dd:epic-decompose <名称>    - 分解Epic为任务"
echo "  5. /dd:task-start <任务ID>      - 开始执行任务"
echo "  6. /dd:code-reflect             - 代码反思和评审"
echo "  7. /dd:task-finish <任务ID>     - 完成任务（用户确认后）"
echo ""
echo "📄 PRD 需求管理命令"
echo "  /dd:prd-new <名称>        - 创建新的产品需求文档"
echo "  /dd:prd-list [选项]       - 列出所有PRD，支持状态筛选"
echo "  /dd:prd-show <名称>       - 查看指定PRD详细内容"
echo "  /dd:prd-parse <名称>      - 将PRD转换为技术实施计划"
echo ""
echo "📚 Epic 技术方案命令"
echo "  /dd:epic-decompose <名称> - 将Epic分解为具体任务（≤10个）"
echo "  /dd:epic-list [选项]      - 显示所有技术实施计划和进度"
echo "  /dd:epic-show <名称>      - 查看Epic详情和技术方案"
echo "  /dd:prd-auto-exec <名称>  - 自动执行PRD的全部任务（AI完整执行）"
echo ""
echo "📝 任务管理命令"
echo "  /dd:task-list [选项]      - 显示任务列表，支持筛选和依赖视图"
echo "  /dd:task-show <PRD名:任务号>    - 查看任务详情和状态信息"
echo "  /dd:task-start <PRD名:任务号>   - 开始执行任务（自动更新Epic进度）"
echo "  /dd:task-resume [PRD名:任务号]  - 继续执行任务（自动更新Epic进度）"
echo "  /dd:task-start-auto <PRD名:任务号> - 自动执行模式（AI持续执行+自动切换任务）"
echo "  /dd:task-resume-auto <PRD名:任务号> - 恢复自动执行模式"
echo "  /dd:task-progress <PRD名:任务号> <描述> - 手动更新任务进度"
echo "  /dd:task-pause <PRD名:任务号>   - 暂停任务，保存执行状态"
echo "  /dd:task-finish <PRD名:任务号>  - 完成任务，进行验收检查"
echo "  /dd:task-set <PRD名:任务号> <操作> [参数] - 管理任务属性和依赖"
echo ""
echo "🔄 工作流管理命令"
echo "  /dd:help                  - 显示此帮助信息"
echo "  /dd:status                - 项目整体状态、统计和健康度评估"
echo "  /dd:code-reflect [--详细] - AI智能代码反思和改进建议"
echo ""
echo "🔗 上下文管理命令"
echo "  /dd:ctx-init              - 创建项目上下文，生成9个基础文档"
echo "  /dd:ctx-load              - 新会话中加载项目上下文"
echo "  /dd:ctx-sync              - 更新项目上下文，反映最新变化"
echo ""
echo "💡 使用提示"
echo "  • 使用 /dd:status 查看项目整体状态"
echo "  • 使用 /dd:task-list --assignable 查找可执行任务"
echo "  • 手动工作流: ctx-init → prd-new → prd-parse → epic-decompose → task-start → code-reflect → task-finish"
echo "  • 自动工作流: ctx-init → prd-new → prd-parse → epic-decompose → prd-auto-exec → code-reflect"
echo "  • 查看 CLAUDE.md 了解完整文档"
echo ""
echo "🎯 建议的下一步操作:"
echo "  • 新项目: /dd:ctx-init (如果还未初始化)"
echo "  • 开始开发: /dd:prd-new <功能名称>"
echo "  • 自动执行: /dd:prd-auto-exec <功能名称>"
echo "  • 查看项目状态: /dd:status"
echo "  • 继续现有工作: /dd:task-resume <PRD名:任务号>"

exit 0