#!/bin/bash

echo "📋 DD任务管理操作"
echo ""
echo "🎯 用法："
echo "  /dd:task-set <任务ID> <操作> [参数]"
echo ""
echo "🔧 支持的操作："
echo "  set-status <状态>     - 设置任务状态（待开始/进行中/已完成/阻塞）"
echo "  set-priority <优先级> - 设置优先级（高/中/低）"
echo "  add-dependency <ID>   - 添加依赖任务"
echo "  remove-dependency <ID>- 移除依赖"
echo "  clear-dependencies    - 清除所有依赖"
echo "  set-effort <工作量>   - 设置预估工作量"
echo "  set-parallel <是否>   - 设置是否可并行（true/false）"
echo "  add-note <内容>       - 添加管理笔记"
echo ""
echo "📝 示例："
echo "  /dd:task-set 001 set-status 进行中"
echo "  /dd:task-set 001 set-priority 高"
echo "  /dd:task-set 001 add-dependency 002,003"
echo ""
echo "⚠️ 注意：此命令仅管理任务属性，不执行代码开发工作"
echo ""
echo "🎯 任务管理后的下一步操作："
echo "  • 开始任务: /dd:task-start <任务ID>"
echo "  • 继续任务: /dd:task-resume <任务ID>"
echo "  • 查看任务状态: /dd:task-show <任务ID>"
echo "  • 查看所有任务: /dd:task-list"