#!/bin/bash

echo "🔄 DD任务继续执行"
echo ""
echo "🎯 功能：继续执行未完成任务，恢复执行上下文"
echo ""
echo "📝 用法："
echo "  /dd:task-resume [任务ID]"
echo "  不指定任务ID时，自动继续最近的未完成任务"
echo ""
echo "🔍 执行流程："
echo "  1. 查找当前未完成任务"
echo "  2. 验证任务状态"
echo "  3. 恢复任务上下文"
echo "  4. 分析执行进度"
echo "  5. 制定继续计划"
echo ""
echo "🧠 智能恢复："
echo "  - 自动重建丢失的上下文文件"
echo "  - 基于Git历史推测进度"
echo "  - 分析遗留问题和阻碍"
echo ""
echo "⚠️ 注意：优先解决遗留问题，确保执行连续性"
echo ""
echo "🎯 任务继续后的下一步操作："
echo "  • 继续执行任务开发工作"
echo "  • 再次暂停: /dd:task-pause <任务ID>"
echo "  • 完成任务: /dd:task-finish <任务ID>"
echo "  • 查看任务状态: /dd:task-show <任务ID>"