#!/bin/bash

echo "🚀 DD任务开始执行"
echo ""
echo "🎯 功能：开始执行指定任务，建立执行上下文"
echo ""
echo "📝 用法："
echo "  /dd:task-start <任务ID>"
echo ""
echo "🔍 执行流程："
echo "  1. 验证任务存在性和状态"
echo "  2. 检查依赖关系"
echo "  3. 建立任务执行上下文"
echo "  4. 智能分析任务内容"
echo "  5. 创建执行计划"
echo ""
echo "🎨 特殊功能："
echo "  - UI任务自动识别设计图片"
echo "  - 智能体辅助任务分析"
echo "  - 执行状态实时跟踪"
echo ""
echo "⚠️ 注意：遵循绝对规则，只提供分析和建议"
echo ""
echo "🎯 任务开始后的下一步操作："
echo "  • 执行任务开发工作"
echo "  • 暂停任务: /dd:task-pause <任务ID>"
echo "  • 完成任务: /dd:task-finish <任务ID>"
echo "  • 查看任务状态: /dd:task-show <任务ID>"